name: Will Thames' tech blog
description: Lessons from working and playing with things like AWS, Ansible, and others
url: http://willthames.github.io
markdown: redcarpet
pygments: true
encoding: utf-8
port: 4002
